package com.example.demo;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity // marks class as a jpa entry -> corresponds to a table in the database
public class Task {
	
	@Id // primary key
	@GeneratedValue(strategy = GenerationType.IDENTITY) // sets primary key to be an auto-incrementing value generated by the database
	private Long id;
	private String title;
	private String description;
	
	public Task() {
		// No-args constructor
	}
	
	public Task(Long id, String title, String description) {
		this.id = id;
		this.title = title;
		this.description = description;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
